- Makefile
Hey @sadov @giggsoff please take a look
> Fixing a few cosmetic issues with Makefile output

- Makefile
Hey @sadov @giggsoff 
This PR makes Makefile more user-friendly, but more importantly it switches us to test with EVE KVM mode which is much, much, much faster than the default Xen one and allows default use of the ACCEL=y (did I mention it is much faster? 😃).
This, in turn, requires switch to the latest EVE release 5.1.10 -- but I hope this is OK, since you guys need to test with the latest anyway.
You can, of course, go back to the previous way of running things by specifying HV=xen and ACCEL=""
> Tweaking Makefile to be more user-friendly

- Makefile
- tests/integration/baseImage_test.go
Some fixes of base image test for adoption of [PR5](https://github.com/lf-edge/eden/pull/5).
> Tweaking Makefile to be more user-friendly fix

- go.mod
- go.sum
- pkg/utils/vnc.go
- tests/integration/application_test.go
Testing of application accessibility via remote console (VNC).
> Remote console testing

- pkg/utils/connectivity.go
- tests/integration/application_test.go
Test that applications can successfully receive cloud init configs.
> Cloud init testing

- Makefile
- cmd/certs.go
- cmd/edenStart.go
- cmd/edenStatus.go
- cmd/edenStop.go
- cmd/ociimage.go
- cmd/qemuconf.go
- cmd/qemurun.go
- cmd/root.go
- cmd/server.go
- go.mod
- go.sum
- images/docker/alpine/dhcpcd.conf
- images/vm/alpine/alpine.yml.in
- pkg/utils/commandWrapper.go
- pkg/utils/connectivity.go
- pkg/utils/container.go
- pkg/utils/eden.go
- pkg/utils/files.go
- pkg/utils/networking.go
- pkg/utils/vnc.go
- pkg/utils/x509.go
Added `start/stop/status` commands to the `eden` tool for manipulation by EVE instance, ADAM controller and EVE local image server.
> eden start/stop/status

- cmd/edenController.go
- cmd/eserver.go
A few nits to guard against directories missing (when we run eden for the first time) @sadov @giggsoff @mydatascience -- please review
> Making image update command more robust

- cmd/changers.go
- cmd/edenController.go
- pkg/controller/cloud.go
- pkg/controller/device.go
This require a bit of refactoring, but I hope it is OK with you @sadov @giggsoff @mydatascience
> Adding get-config to the controller/edge-node

- pkg/controller/adam/adam.go
- pkg/controller/cachers/base.go
- pkg/controller/cachers/fileCache.go
- pkg/controller/cachers/redisCache.go
- pkg/controller/loaders/base.go
- pkg/controller/loaders/fileLoader.go
- pkg/controller/loaders/redisLoader.go
- pkg/controller/loaders/remoteLoader.go
- pkg/utils/config.go
Caching of info/logs to Redis or local files. Related to https://github.com/lf-edge/eden/issues/42.
> Redis-based info/logs caching

- Makefile
- cmd/adam.go
- cmd/certs.go
- cmd/confchanger.go
- cmd/downloader.go
- cmd/edenClean.go
- cmd/edenConfig.go
- cmd/edenController.go
- cmd/edenEVEUpdate.go
- cmd/edenReconf.go
- cmd/edenSetup.go
- cmd/edenStart.go
- cmd/edenStatus.go
- cmd/edenStop.go
- cmd/eserver.go
- cmd/redis.go
- cmd/root.go
- go.mod
- pkg/utils/config.go
- pkg/utils/context.go
Makes possible to use different EVE config variants.
> Config contexts

- pkg/defaults/defaults.go
- pkg/utils/config.go
- pkg/utils/container.go
Organization of an internal docker network between components. Checking for docker images in the cache before pull.
> Adaptation for firewall

- Makefile
- cmd/edenConfig.go
- pkg/defaults/defaults.go
Added `set key`,`get --all` and `reset`. Removed `--name` option for fix https://github.com/lf-edge/eden/issues/72 and https://github.com/lf-edge/eden/issues/73.
> 'eden config' improvement

- cmd/edenStatus.go
- pkg/controller/functions.go
- pkg/utils/commandWrapper.go
- pkg/utils/container.go
- pkg/utils/eden.go
'Status' related part of splited https://github.com/itmo-eve/eden/pull/11
> Improved 'eden status' command output

- cmd/changers.go
- cmd/edenConfig.go
- cmd/edenController.go
- cmd/eve.go
- pkg/defaults/defaults.go
- pkg/utils/files.go
Eden commands adaptation for https://wiki.lfedge.org/display/EVE/Eden+Workflows, fix https://github.com/lf-edge/eden/issues/74.
> Eden commands fixes

- cmd/edenController.go
- cmd/edenPod.go
- cmd/root.go
- pkg/controller/application.go
- pkg/controller/cloud.go
- pkg/controller/datastore.go
- pkg/controller/device.go
- pkg/controller/image.go
- pkg/controller/networkInstance.go
- pkg/defaults/defaults.go
- pkg/expect/application.go
- pkg/expect/datastore.go
- pkg/expect/expectation.go
- pkg/expect/image.go
- pkg/expect/networkInstance.go
- pkg/utils/networking.go
- pkg/utils/params.go
Test of application containers operations by `eden pod` command.
> Application contatiners

- cmd/edenConfig.go
- pkg/controller/adam/adam.go
- pkg/controller/functions.go
- pkg/utils/config.go
Remove automagical config creation for avoiding unpredictional effects. Changing of some messages.
> Autoconfig removing

- Makefile
- cmd/edenController.go
- cmd/edenReconf.go
- cmd/info.go
- cmd/log.go
- pkg/controller/adam/adam.go
- pkg/controller/cloud.go
- pkg/controller/controller.go
- pkg/controller/devModel.go
- pkg/controller/device.go
- pkg/controller/functions.go
- pkg/controller/types/types.go
- pkg/defaults/defaults.go
- pkg/device/device.go
- pkg/projects/edgeNodeDescription.go
- pkg/projects/project.go
- pkg/projects/testContext.go
- pkg/utils/config.go
- pkg/utils/configDiff.go
- tests/Makefile
- tests/integration/controller_test.go
- tests/reboot/Makefile
- tests/reboot/eden-config.tmpl
- tests/reboot/eden.reboot.tests.txt
- tests/reboot/reboot_test.go
- tests/units/templates_test.go
Implementation of TestContexts accordingly https://wiki.lfedge.org/display/EVE/EVE+Integration+Testing.
The implementation of Asserts is planned and some optimization of API function calls is planned for the next PR.
> Test сontexts

- Makefile
- cmd/edenClean.go
- cmd/edenConfig.go
- pkg/utils/eden.go
Fixes for https://github.com/lf-edge/eden/issues/68 and https://github.com/lf-edge/eden/issues/73
> Mandatory config delete and eden clean refactoring

- pkg/projects/state.go
- pkg/projects/testContext.go
- tests/reboot/reboot_test.go
Added states to SDK https://wiki.lfedge.org/display/EVE/Objects+and+methods+for+SDK, https://github.com/lf-edge/eden/issues/108
> state implementation

- pkg/projects/state.go
- pkg/projects/testContext.go
Fixed the problem of "states" with a quick reboot during TestReboot.
> fix reboot test

- pkg/defaults/defaults.go
> fix rootfs pattern for rpi

- cmd/eve.go
Fix for https://github.com/lf-edge/eden/issues/123
> ssh key set on every eden eve ssh

- cmd/edenStatus.go
> last info received time

- cmd/eve.go
- pkg/defaults/defaults.go
- pkg/utils/config.go
- pkg/utils/configDiff.go
- tests/lim/eden-config.tmpl
- tests/reboot/eden-config.tmpl
Fix. for https://github.com/lf-edge/eden/issues/123#issuecomment-651386687 2.
> fix EVE naming

- pkg/expect/application.go
- pkg/expect/datastore.go
- pkg/expect/docker.go
- pkg/expect/expectation.go
- pkg/expect/http.go
- pkg/expect/image.go
- pkg/expect/networkInstance.go
- pkg/expect/vm.go
Here are some comments for godoc documentation for Expect pkg module.
#140 
> Comments for Expect pkg module  

- go.mod
- go.sum
- pkg/controller/device.go
- pkg/defaults/defaults.go
This PR adds Volumes and Content support to Eden & supports EVE 5.7.0 functionality
#130 
> Support 5.7.0 Implement Volumes and Content

- cmd/edenConfig.go
- cmd/edenStart.go
- cmd/edenStatus.go
- cmd/edenStop.go
- cmd/eve.go
- go.mod
- go.sum
- pkg/controller/application.go
- pkg/controller/device.go
- pkg/controller/functions.go
- pkg/controller/network.go
- pkg/controller/networkInstance.go
- pkg/defaults/defaults.go
- pkg/device/device.go
- pkg/projects/edgeNodeDescription.go
- pkg/projects/state.go
- pkg/projects/testContext.go
- pkg/projects/testProc.go
- pkg/utils/config.go
- pkg/utils/configDiff.go
- tests/docker/Makefile
- tests/docker/docker_test.go
- tests/docker/eden-config.tmpl
- tests/docker/eden.docker.tests.txt
This is a test that tests deployment of docker container with nginx and checks that nginx is running and available.
Then it deletes the container
Also adding functions of getEveIP to State and AddProcTimer that calls some function regularily before it returns not nil
> docker test implementation

- cmd/edenSetup.go
- go.mod
- go.sum
- pkg/defaults/defaults.go
- pkg/utils/eden.go
This supports Eve version 5.7.1 vs older 5.7.0
> 5.7.1 support fix

- pkg/expect/baseOSImage.go
- pkg/utils/eden.go
- pkg/utils/networking.go
> fix timeouts of eserver file upload

- cmd/adam.go
- cmd/certs.go
- cmd/confchanger.go
- cmd/downloader.go
- cmd/edenClean.go
- cmd/edenConfig.go
- cmd/edenController.go
- cmd/edenPod.go
- cmd/edenReconf.go
- cmd/edenSetup.go
- cmd/edenStart.go
- cmd/edenStatus.go
- cmd/edenStop.go
- cmd/eserver.go
- cmd/eve.go
- cmd/info.go
- cmd/log.go
- cmd/metric.go
- cmd/redis.go
- cmd/root.go
assingCobraToViper -> assignCobraToViper 
> Fixed typo for assignCobraToViper

- cmd/eve.go
adding `eden eve version` that obtains the version from ADAM and displays it
> eve version CLI command

- README.md
> Update Readme to include a how-to get an EVE version and syslog from SD card

- tests/vnc/vnc_test.go
We can set image to test with:
./eden test tests/vnc -v debug -a '-applink http://naulinux.ru/static/Projects/EDEN/alpine-%s.qcow2'
Also includes fix for vncDisplay default number 0->1
> Vnc test has now a param of image  + fix for vncDisplay

- cmd/edenTest.go
Both in Shell (#) and Go-style (//).
> Added line comments support to test scenarios.

- cmd/edenController.go
- cmd/edenPod.go
- pkg/expect/application.go
- pkg/expect/docker.go
- pkg/expect/expectation.go
- pkg/expect/networkInstance.go
- pkg/expect/options.go
- pkg/expect/vm.go
- pkg/utils/config.go
- tests/docker/docker_test.go
- tests/vnc/vnc_test.go
Changing expect package to support app parameters 
Implemented vncdisplay, netinstance, resources, disksize options
> Expect package support of app`s parameters

- tests/docker/docker_test.go
Flags for docker binary test for customizing behavior and support multiple tests with different forwarded port running at the same time.
```
name= flag.String("name", "", "Name of app, random if empty")
externalPort = flag.Int("externalPort", 8028, "Port for access app from outside of EVE")
internalPort = flag.Int("internalPort", 80, "Port for access app inside EVE")
appLink      = flag.String("appLink", "docker://nginx", "Link to get app")
portPublish  []string
```
Signed-off-by: Petr Fedchenkov giggsoff@gmail.com
> docker test flags

- Makefile
A temporary fix before CircleCI is in place. 
Will build docker image for eserver locally
> build eserver docker image in  make bin 

- cmd/edenPod.go
- pkg/controller/einfo/einfo.go
- pkg/controller/elog/elog.go
- pkg/controller/emetric/emetric.go
- pkg/utils/queue.go
./eden pod logs implemented
You can use --tail N for get only N lines
You can define --fields=log to get only logs
Signed-off-by: Petr Fedchenkov giggsoff@gmail.com
> pod logs command

- cmd/edenPod.go
Enables to attach networks while using `pod deploy` command
> pod deploy -networks

- cmd/edenPod.go
Includes UUID into output
Support multiple network IPs
Fix bugs with recreating of APPs with the same names
Signed-off-by: Petr Fedchenkov giggsoff@gmail.com
> pod ps fixes

- tests/workflow/testdata/eden_setup.txt
> sync setup stdout

- cmd/edenStatus.go
- cmd/eve.go
Updated the status so now for a local Eve it also displays the time last seen and info from remote
#126
> Updated status command for local qemu  eve to get state from info

- cmd/edenStatus.go
- cmd/eve.go
- tests/workflow/testdata/eden_stop.txt
Fix eden stop workflow and status processing on stopped eden
> Fix status

- README.md
- docs/adam.md
- docs/cloud.md
- docs/config.md
- docs/eserver.md
- docs/flow.md
As discussed on Slack with @giggsoff
> add lots of docs

- tests/network/Makefile
- tests/network/README.md
- tests/network/eden-config.tmpl
- tests/network/eden.network.tests.txt
- tests/network/image/Dockerfile
- tests/network/image/dhcpcd.conf
- tests/network/image/entrypoint.sh
- tests/network/image/supervisord.conf
- tests/network/testdata/deploy_app.txt
- tests/network/testdata/test_networking.txt
- tests/workflow/eden.workflow.tests.txt
This test creates and assignes a network to 2 applications, which communicate.  One has nginx, the other uses curl. 
Adding network test to workflow.
The test contains container description 
Passed workflow.
> test networking & app communication

- cmd/edenStart.go
> fix broken command

- LICENSE
- NOTICE.md
- README.md
- cmd/edenGcp.go
- cmd/edenUtils.go
- go.mod
- go.sum
- pkg/defaults/defaults.go
- pkg/linuxkit/gcp.go
- pkg/linuxkit/metadata.go
- pkg/linuxkit/util.go
- pkg/utils/config.go
- pkg/utils/configDiff.go
Integration of linuxkit
Sub-commands to work with GCP via linuxkit
> Linuxkit integration

- cmd/edenPod.go
- pkg/expect/application.go
- pkg/expect/expectation.go
- pkg/expect/options.go
Add ability to set access for app only to external networks, not local ones
> acl for apps

- pkg/defaults/defaults.go
- tests/network/testdata/deploy_app.txt
- tests/network/testdata/test_networking.txt
adds the third app with host-only network
> firewall test in network test

- Makefile
Just to make it easier to run from different places.
> install option to go path

- Makefile
- pkg/defaults/defaults.go
We need to enlarge volume size by default.
> expand size for volumes

- cmd/edenStatus.go
- cmd/eve.go
- go.mod
- go.sum
Just for ease of instant viewing.
> Nice status indicators

- cmd/edenPod.go
- pkg/expect/expectation.go
nohyper for pod deploy
fix multiple ports mapping
> no-hyper and multiple ports

- pkg/expect/docker.go
when looking to obtain the volume info for a docker image, we only need the config, but we were pulling the whole image. For large images, that is a big waste. In any case, there was no need to involve docker anyways.
This just pulls the config itself and parses it.
Thanks to @giggsoff for explaining the requirements.
> pull only config when we don't need whole image

- cmd/eve.go
- pkg/defaults/defaults.go
Move to q35 machine for qemu
https://github.com/lf-edge/eve/pull/1411
> q35 machine

- go.mod
- go.sum
- pkg/defaults/defaults.go
- tests/phoronix/Makefile
- tests/phoronix/eden-config.tmpl
- tests/phoronix/eden.phoronix.tests.txt
- tests/phoronix/image/Dockerfile
- tests/phoronix/image/entrypoint.sh
- tests/phoronix/testdata/deploy_app.txt
- tests/phoronix/testdata/test_phoronix.txt
Phoronix tests in docker.
You can run it by `./eden test tests/phoronix/ -v debug` or `./eden test tests/phoronix/ -v debug -a="benchmark=pts/coremark-1.0.0"`
Needs https://github.com/lf-edge/eve/pull/1405 to work.
> phoronix Docker

- Makefile
- README.md
Updating Readme for #260 #259 #257 
> Updated makefile and gcp README

- README.md
> Fixing Quickstart in README

- README.md
Readme for `eden clean` command
> clean command readme

- cmd/edenStatus.go
- cmd/eve.go
Fix attempt to receive requests while stopped Adam
> fix requests while stopped

- README.md
- cmd/edenPod.go
- pkg/controller/adam/adam.go
- pkg/controller/adam/loaders.go
- pkg/controller/controller.go
- pkg/controller/eapps/eappslog.go
- pkg/controller/loaders/base.go
- pkg/controller/loaders/fileLoader.go
- pkg/controller/loaders/redisLoader.go
- pkg/controller/loaders/remoteLoader.go
- pkg/controller/types/types.go
- pkg/defaults/defaults.go
Implementation of displaying logs of applications
> app logs loader

- README.md
- cmd/eve.go
> ssh command

- cmd/certs.go
- pkg/defaults/defaults.go
- pkg/eden/eden.go
- pkg/utils/container.go
Move to environment variables to pass cert and key into Adam.
#266 
> environment variables for Adam cert and key

- Makefile
- eserver/pkg/manager/manager.go
- pkg/defaults/defaults.go
Seems, that http download inside eserver had the issue with sha caclulation.
> fix eserver http sha calculation

- cmd/certs.go
- cmd/edenClean.go
- pkg/eden/eden.go
- pkg/utils/x509.go
Fix problems with certificate creation
Fix restart Adam before removing certs
> fix certs creation process and restart adam during cleanup

- tests/reboot/reboot_test.go
Change from 1 min to 10 min default timeout
> Increased reboot test default timeout

- cmd/downloader.go
- cmd/edenSetup.go
- pkg/defaults/defaults.go
- pkg/utils/config.go
- pkg/utils/downloaders.go
- tests/integration/baseImage_test.go
Adds ability to define registry to download EVE image from.
> registry to download EVE from

- cmd/edenPod.go
Displaying download percentage in `pod ps`
> show percent of download progress

- docs/eve-images.md
- pkg/utils/networking.go
Seems, that Adam need some time to stabilize internal cache with redis https://github.com/lf-edge/eden/issues/289#issuecomment-703128160. So, we need to check response code and repeat if needed.
Also, include fixes in Readme.
> check of the status code of the response from Adam to stabilize

- README.md
> windows for RPi4 readme

- cmd/eve.go
> fix garbage string in ssh

- tests/network/testdata/test_networking.txt
> wait for apps teardown

- pkg/linuxkit/gcp.go
> fix gcp waiting

- tests/docker/testdata/2dockers_test.txt
- tests/network/testdata/deploy_app.txt
> reduce memory for tests

- go.mod
- go.sum
- pkg/defaults/defaults.go
> new version sync

- tests/workflow/eden.workflow.tests.txt
> temp disabling networking test

- README.md
- cmd/edenExportImport.go
- cmd/eve.go
- cmd/root.go
- pkg/controller/adam/adam.go
- pkg/controller/adam/httpclient.go
- pkg/controller/controller.go
- pkg/device/device.go
- pkg/utils/config.go
- pkg/utils/configDiff.go
- pkg/utils/networking.go
- pkg/utils/tar.go
Support for `./eden utils export file.tar.gz` and `./eden utils import file.tar.gz`.
In the process of writing comments and readme
> export/import functionality for Eden

- pkg/projects/testProc.go
- tests/vnc/vnc_test.go
> vnc and ssh test

- tests/vnc/vnc_test.go
> fix ip, expand timeout, add multicore

- pkg/defaults/defaults.go
- tests/phoronix/Makefile
- tests/phoronix/eden.phoronix.tests.txt
- tests/phoronix/image/Dockerfile
- tests/phoronix/image/defs/fio-basic/suite-definition.xml
- tests/phoronix/image/entrypoint.sh
- tests/phoronix/testdata/deploy_app.txt
- tests/phoronix/testdata/test_phoronix.txt
Move phoronix fio test to qcow2.
Expand timeout.
> phoronix test qcow2

- .github/ISSUE_TEMPLATE.md
- .github/workflows/eden.yml
> workflow action

- docs/flow.md
Explains how to:
* deploy containers of all types - docker, VM from URL, VM from file, VM from OCI image
* update the EVE image
> update for basic flow instructions

- tests/network/Makefile
- tests/network/image/Dockerfile
- tests/network/image/entrypoint.sh
- tests/network/image/supervisord.conf
- tests/network/testdata/deploy_app.txt
- tests/network/testdata/test_networking.txt
- tests/workflow/eden.workflow.tests.txt
> expand teardown timeout

- pkg/projects/testContext.go
> fix duration units

- tests/network/testdata/test_networking.txt
> Refactoring the network test to use the application state detector.

- tests/app/testdata/2dockers_test.txt
- tests/docker/testdata/2dockers_test.txt
> 2docker tests fix for Jenkins test

- tests/workflow/eden.workflow.tests.txt
Set several types of workflows:
large
small
default
> updated workflows 

- tests/workflow/testdata/ssh.txt
> get IP from status

- tests/workflow/testdata/eden_stop.txt
> Support external eve

- tests/vnc/vnc_test.go
We need to expand defaults for future tests on travis-ci
> expand vnc

- cmd/edenTest.go
We need to log periodically to avoid stopping travis-ci.
> test is running notification

- pkg/utils/config.go
- pkg/utils/configDiff.go
- tests/workflow/testdata/ssh.txt
> fix ssh test for another hostfwd

- .yetus/excludes.txt
- go.mod
- go.sum
- pkg/defaults/defaults.go
> new eve tag

- tests/eclient/eden.eclient.tests.txt
- tests/eclient/testdata/host-only.txt
- tests/workflow/eden.workflow.tests.txt
Just ping's from common and host-only application containers.
> Host-only ACL test

- cmd/edenStatus.go
- cmd/eve.go
> eden eve ip

- README.md
- cmd/edenNetwork.go
- cmd/edenPod.go
- cmd/podModify.go
- pkg/expect/application.go
- pkg/expect/docker.go
- pkg/expect/expectation.go
- pkg/expect/networkInstance.go
- pkg/expect/options.go
Initial support for ports of pods modify
> pod modify initial

- tests/workflow/eden.workflow.tests.txt
We need to fix Eden or Eve. 2 docker test start failing. Before we understand why 
> Temp remove docker test

- cmd/edenNetwork.go
- cmd/edenPod.go
- cmd/edenTest.go
- cmd/lists.go
- pkg/controller/device.go
Show pod ps. network ls and config during tests.
> debug info

- tests/eclient/eden.eclient.tests.txt
- tests/eclient/testdata/eclient.txt
- tests/eclient/testdata/host-only.txt
- tests/eclient/testdata/maridb.txt
- tests/eclient/testdata/networking_light.txt
- tests/eclient/testdata/ngnix.txt
- tests/eclient/testdata/nw_switch.txt
- tests/eclient/testdata/port_switch.txt
Added tests for switching of app's networks and ports redirection:
```
eden test tests/eclient/ -v debug
```
> Network switch tests

- cmd/edenTest.go
- pkg/controller/device.go
- pkg/controller/loaders/redisLoader.go
- pkg/expect/datastore.go
- pkg/expect/docker.go
- pkg/expect/image.go
- pkg/projects/testContext.go
- pkg/projects/testProc.go
- pkg/utils/state.go
- tests/app/app_test.go
- tests/app/testdata/2dockers_test.txt
- tests/eclient/testdata/eclient.txt
- tests/eclient/testdata/host-only.txt
- tests/eclient/testdata/maridb.txt
- tests/eclient/testdata/networking_light.txt
- tests/eclient/testdata/ngnix.txt
- tests/escript/go-internal/testscript/cmd.go
- tests/network/testdata/deploy_app.txt
- tests/phoronix/testdata/deploy_app.txt
- tests/workflow/testdata/deploy_docker_eden.txt
- reduce verbosity of pod deploy
- print last deployed config in stdout
- implement information about assertion inside app.test detector
> fixes for better reading of output

- pkg/controller/functions.go
- pkg/defaults/defaults.go
- pkg/utils/config.go
The ability to set loglevel in the config
> loglevel in config

- cmd/edenSetup.go
- cmd/eve.go
- tests/network/testdata/test_networking.txt
> [wip] cut in bash and fixes for darwin

- README.md
> Fixing Quickstart - Adding workflow by defaut

- Makefile
- tests/app/Makefile
- tests/docker/Makefile
- tests/escript/Makefile
- tests/lim/Makefile
- tests/reboot/Makefile
- tests/vnc/Makefile
Move from absolute to relative symlinks
> relative links

- README.md
- cmd/edenConfig.go
- cmd/edenSetup.go
- go.mod
- go.sum
- pkg/defaults/defaults.go
Update EVE tag and sync rpi with upstream.
> update eve and rpi

- README.md
Added make clean & docker test instead of workflow 
> make sure README Quickstart runs.

- pkg/defaults/defaults.go
- tests/workflow/eden.workflow.tests.txt
> return 2docker-test

- pkg/defaults/defaults.go
- tests/vnc/vnc_test.go
Adds password to VNC test #374 
> vnc password in VNC test

- README.md
notes for #383 #382 #381 #380 inside Readme
> fixes in README.md

- tests/io_perfomance/testdata/deploy_app.txt
- tests/io_perfomance/testdata/fio_tests.txt
> fixes for fio test

- pkg/utils/commandWrapper.go
Wait for unexpected exit of the process
#382 
> wait for process

- tests/io_perfomance/Makefile
- tests/io_perfomance/image/README.md
- tests/io_perfomance/image/run-test.sh
- tests/io_perfomance/testdata/fio_tests.txt
Add GIT_BRANCH parameter for debugging mode.
Add checks test results on GitHub
Add new version container
> Fio tests update

- tests/flir/Makefile
- tests/flir/eden-config.tmpl
- tests/flir/eden.flir.tests.txt
- tests/flir/image/Dockerfile
- tests/flir/testdata/deploy_app.txt
- tests/flir/testdata/test_flir.txt
Signed-off-by: Ruslan Dautov <dautovri@hpcdlab.com>
> fledge test with flir camera

- cmd/changers.go
- cmd/edenController.go
- docs/config.md
- docs/flow.md
- go.mod
- go.sum
- pkg/defaults/defaults.go
> image update and few notes on update config

- docs/tests.md
Add Documentation about tests in Eden
> Add Documentation about tests in Eden

- cmd/debug.go
- docs/debug.md
The ability to run multiple perf on EVE with different parameters
> parameter to save perf output for debug

- docs/test-examples.md
Just some examples of running tests.
> Examples of running tests

- cmd/edenStatus.go
> status all

- README.md
> Changed Readme for firewall

- .github/workflows/release.yml
Adding github action for eden build and publish  to github Releases once tagged
> Autobuild and autopublish for Releases

- cmd/edenPod.go
- cmd/log.go
- go.mod
- go.sum
- pkg/controller/device.go
- pkg/controller/eapps/eappslog.go
- pkg/controller/einfo/einfo.go
- pkg/controller/elog/elog.go
- pkg/controller/emetric/emetric.go
- pkg/controller/erequest/erequest.go
- pkg/controller/functions.go
- pkg/controller/loaders/redisLoader.go
- pkg/defaults/defaults.go
- pkg/projects/testProc.go
- tests/lim/lim_test.go
- tests/lim/testdata/log_test.txt
> newlog support

- .github/workflows/release.yml
> Fixing a typo

- .github/workflows/release.yml
- .github/workflows/yetus.yml
> Updating Yetus to a recently released 0.13.0

- README.md
- cmd/registry.go
- tests/registry/Makefile
- tests/registry/README.md
- tests/registry/eden-config.tmpl
- tests/registry/eden.registry.tests.txt
- tests/registry/testdata/registry_test.txt
- tests/workflow/eden.workflow.tests.txt
> registry test

- .github/workflows/release.yml
- README.md
Fix yetus for README
Fix dependencies and activation for release
> Fix for Readme & release.yml

- .github/workflows/release.yml
> adding release fix for publishing

- tests/workflow/eden.workflow.tests.txt
> fix registry test in workflow

- README.md
- cmd/edenConfig.go
- cmd/edenPod.go
- cmd/edenSetup.go
- cmd/lists.go
- go.mod
- go.sum
- pkg/controller/devModel.go
- pkg/defaults/defaults.go
- pkg/utils/config.go
- pkg/utils/downloaders.go
- tests/vnc/vnc_test.go
- tests/workflow/testdata/eden_setup.txt
General device model for remote devices.
> general device model

- README.md
Fix Quickstart to run small workload and do not  run setup-onboard tests after quickstart commands
> fix quickstart

- cmd/info.go
- cmd/log.go
- cmd/metric.go
Show last N lines in log/metric/info with `tail` flag.
> show last N lines in log/metric/info

- .github/workflows/release.yml
Action to build and publish eden-http-server image
> build eden-http-server

- pkg/utils/config.go
> ssid in config

- cmd/edenConfig.go
- cmd/edenGcp.go
- pkg/linuxkit/gcp.go
- pkg/projects/testContext.go
- pkg/utils/config.go
- tests/reboot/reboot_test.go
> fixes for multiple Eden

- cmd/certs.go
- cmd/edenClean.go
- cmd/edenSetup.go
- cmd/edenStart.go
- cmd/edenStop.go
- cmd/eve.go
- go.mod
- go.sum
- pkg/eden/eden.go
- pkg/utils/container.go
Remove nested calls from`pkg/eden` back to `cmd` and some refactoring. Part of #430 
> Remove nested calls for cmd

- Makefile
- README.md
- cmd/edenGcp.go
- cmd/edenSetup.go
- go.mod
- pkg/controller/functions.go
- pkg/linuxkit/gcp.go
- tests/flir/README.md
Fixes for yetus warnings (from `make yetus`).
`eden utils vm log` command to see console output from gcp instance
> yetus fixes and gcp log

- cmd/edenNetwork.go
- cmd/edenPod.go
- pkg/eve/applications.go
- pkg/eve/networks.go
- pkg/eve/state.go
- pkg/eve/volumes.go
Memory usage in pod ps, traffic in network ls and reference (app name) in volume ls.
> more info in pod ps, network ls and volume ls

- cmd/edenGcp.go
- pkg/defaults/defaults.go
- pkg/linuxkit/gcp.go
Delete firewall rule from gcp before adding new one.
Priority set for firewall rule.
> remove gcp firewall rule before add

- cmd/edenVolume.go
- cmd/eve.go
- pkg/controller/device.go
- pkg/expect/volume.go
- tests/volume/Makefile
- tests/volume/README.md
- tests/volume/eden-config.yml
- tests/volume/eden.vol.tests.txt
- tests/volume/testdata/volumes_test.txt
- tests/volume/vol_test.go
`eden test tests/volume/ -v debug`
Still EVE architectural problems with multiply running of state detector -- try to uncomment line:
https://github.com/itmo-eve/eden/blob/deceed492d30cdef6b0d0b9794387ad95d77edff/tests/volume/testdata/volumes_test.txt#L12
> Volume test

- cmd/edenVolume.go
- cmd/eve.go
- pkg/controller/device.go
- pkg/expect/volume.go
`eden volume create` and `eden volume delete` commands.
> [WIP] eden volume create and delete

- pkg/tests/functions.go
> Test args passing fix

- tests/io_perfomance/Makefile
- tests/io_perfomance/image/Dockerfile
- tests/io_perfomance/image/fioconv.go
- tests/io_perfomance/image/run-test.sh
- tests/io_perfomance/testdata/fio_tests.txt
> IO test performance update

- tests/lim/testdata/info_test.txt
- tests/lim/testdata/metric_test.txt
> reduce info and metric timewait

- tests/eclient/eden+ports.sh
- tests/eclient/eden-ports.sh
- tests/eclient/testdata/eclients.txt
- tests/workflow/eden.workflow.tests.txt
Testing the maximum application limit with params on env. vars:
* EDEN_TEST_APPS by default = 20
* EDEN_TEST_TIME by default = 30 min
* EDEN_TEST_IMG by default = docker://itmoeve/eclient:3
For example:
```
EDEN_TEST_APPS=50 EDEN_TEST_TIME=1h eden test tests/eclient -p eden.escript.test -r TestEdenScripts/eclients -t 1h -v debug
```
> Apps limit test

- .github/workflows/eden_gcp.yml
- tests/workflow/eden.workflow.tests.txt
Using github Actions to launch EVE on GCP for testing VMs 
One Needs GITHUB secrets 
GCP_PROJECT_ID - google project ID 
GCP_SA_KEY - google project json key 
OVPN_FILE - openvpn file 
Also added new "gcp" workflow as large workflow is too large 
> Added test on GCP & gcp workflow

- cmd/debug.go
- cmd/eve.go
- docs/debug.md
- pkg/defaults/defaults.go
Add `eden utils debug hw <file>` command.
> lshw in debug container

- cmd/edenConfig.go
> Default setting for 'eden config add'

- .github/workflows/eden_gcp.yml
- README.md
- docs/usb-pt.md
- pkg/defaults/defaults.go
- pkg/linuxkit/gcp.go
- tests/app/app_test.go
- tests/eclient/testdata/nw_switch.txt
- tests/network/nw_test.go
- tests/vnc/vnc_test.go
- tests/volume/vol_test.go
Implementation of strategy matrix for test xen and kvm variants on gcp.
> xen testing in Eden workflow

- tests/app/app_test.go
- tests/vnc/vnc_test.go
Print logs of apps inside detectors in case of timeout.
> app logs print inside detectors

- pkg/expect/http.go
Seems, that we broke loading of local files
> fix datastore for file

- pkg/defaults/images.go
We need to sync our library of images with new versions.
> sync image library with images from tests

- tests/escript/testdata/nested_scripts.txt
> Fix for nested_scripts

- tests/volume/vol_test.go
We need to initialize eveState before feeding new values in volume detector
> initialize eveState before feeding new values in volume detector

- README.md
- cmd/edenClean.go
- cmd/edenConfig.go
- cmd/edenSetup.go
- cmd/edenStart.go
- cmd/edenStop.go
- cmd/eve.go
- pkg/defaults/defaults.go
- pkg/eden/eden.go
- pkg/models/devModel.go
- pkg/models/vbox.go
- pkg/utils/downloaders.go
Signed-off-by: Ruslan Dautov <dautovri@hpcdlab.com>
Tested on MacOS Big Sur and Ubuntu. VirtualBox 6.1
- eden packager creating vdi images 
- new devModel VBox
- eden setup with VDI images 
- Eden Start and Stop modification to support new devModel
> eden Virtual Box support

- tests/io_performance/testdata/fio_tests.txt
Adds the required variable (GIT_FOLDER) to the test run script
> Fix start test io_performance

- .github/workflows/eden_gcp.yml
Use curl in action to obtain ip.
> remove external action

- pkg/eden/eden.go
- pkg/utils/commandWrapper.go
New logic of starting Virtual Box VM to pass tests with ports configs 
DevModel =  VBox 
Signed-off-by: Ruslan Dautov <dautovri@hpcdlab.com>
> VirtualBox fix for ports changing

- cmd/edenClean.go
- cmd/edenStatus.go
- cmd/eve.go
- pkg/eden/eden.go
- tests/workflow/eden.workflow.tests.txt
- tests/workflow/testdata/eve_restart.txt
> fixes for VBox

- cmd/edenStart.go
- cmd/edenStatus.go
- cmd/eve.go
- docs/parallels.md
- pkg/defaults/defaults.go
- pkg/defaults/templates.go
- pkg/eden/eden.go
- pkg/models/devModel.go
- pkg/models/parallels.go
- pkg/utils/downloaders.go
- tests/workflow/eden.workflow.tests.txt
- tests/workflow/testdata/eden_reset.txt
Parallels support for Eden.
To start with EDEN you should do the following steps:
```bash
eden config add default --devmodel=parallels
eden setup
eden start
eden eve onboard
```
> Parallels support

- .github/workflows/eden_setup.yml
Add the action that checks all setups - so we don't have errors for producing eve images for different devmodels
> Added setup action

- tests/io_performance/image/README.md
- tests/io_performance/image/mkconfig/mkconfig.go
- tests/io_performance/image/run-test.sh
- tests/io_performance/testdata/fio_tests.txt
- Added an environment variable to indicate the path in the repository where the results will be placed
- Increased io depth in a default value from 16 to 32
- Updated README.md
> Fix create folder in io_performance test

- cmd/edenSetup.go
Add public IP to eserver and publish ipxe file
> Public IP for eserver and IPXE cfg file for eserver

- eserver/Dockerfile
> Bumping alpine package version

- docs/io-performance-tests.md
- tests/io_performance/image/README.md
- tests/io_performance/image/run-test.sh
Сhanges:
- Now the container can be started without environmental variables
- Added documentation to the io_performance test
- Fixed a bug with uploading results to Github if the GIT_PATH environment variable was specified
- The README.md file has been updated.
> Fix upload results to github and add documentation about io_performance test

- docs/io-performance-tests.md
- tests/io_performance/image/mkconfig/mkconfig.go
- tests/io_performance/image/run-iostat.sh
- tests/io_performance/image/run-test.sh
- Add saving of io_performance test results locally
- Fix error with GIT_REPO env
> Add saving of io_performance test results locally

- README.md
- pkg/defaults/defaults.go
- pkg/eden/eden.go
Enable EVE in QEMU on ARM64
Signed-off-by: Sergey Temerkhanov <s.temerkhanov@gmail.com>
> QEMU: Enable QEMU virtualization on AARCH64

- pkg/projects/testProc.go
- pkg/utils/format.go
- tests/app/app_test.go
- tests/docker/docker_test.go
- tests/lim/lim_test.go
- tests/network/nw_test.go
- tests/reboot/reboot_test.go
- tests/vnc/vnc_test.go
- tests/volume/vol_test.go
Adds timestamps to output of tests to track what happens in what time.
> timestamp for tests

- .github/workflows/eden_gcp.yml
check exit code of getting IP and firewall from gcp
adds info to artifacts
> eden_gcp workflow fixes

- docs/io-performance-tests.md
- tests/io_performance/image/mkconfig/mkconfig.go
- Added environment variable - FIO_CHECKSUMM
- Updated documentation _io-performance-tests.md_
> Add parameter to check the integrity of the write data.

- .github/workflows/eden.yml
- pkg/eden/eden.go
The ability to save output from console to file and save it in artifact.
> show info and console output inside artifacts

- .github/workflows/eden_gcp.yml
- pkg/linuxkit/gcp.go
Troubleshooting failing eden actions
> More verbose messages on setup stage

- tests/escript/go-internal/testscript/testscript.go
Initial support for GitHub annotations
In case of error Eden will add `::error` which will be added into GH annotation.
> GH annotation

- cmd/edenGcp.go
- pkg/linuxkit/gcp.go
We should process information about instance creation status from GCP.
> poll instance creation status from gcp

- tests/eclient/Makefile
- tests/eclient/image/Dockerfile
- tests/eclient/testdata/disk.txt
- tests/eclient/testdata/eclient.txt
- tests/eclient/testdata/eclients.txt
- tests/eclient/testdata/host-only.txt
- tests/eclient/testdata/maridb.txt
- tests/eclient/testdata/networking_light.txt
- tests/eclient/testdata/ngnix.txt
- tests/eclient/testdata/nw_switch.txt
- tests/eclient/testdata/usb-pt_test.txt
- tests/volume/testdata/volumes_test.txt
BusyBox and lshw added
Upgrade eclient image version from 0.3 to 0.4 in tests 
Signed-off-by: Ruslan Dautov <dautovri@hpcdlab.com>
> Docker Image update eclient image(tests)

- eserver/Dockerfile
Update package version inside eserver image
> update dependency version

- .github/workflows/eden_gcp.yml
Seems, I added incorrect command in previous PR. We should save log from gcp.
> fix collect logs step

- .github/workflows/eden.yml
- .github/workflows/eden_gcp.yml
Check for networks overlap before test
> check for overlap

- docs/test-examples.md
- pkg/defaults/defaults.go
- pkg/expect/http.go
- pkg/utils/files.go
- tests/escript/go-internal/testscript/exe.go
- tests/lim/lim_test.go
- tests/update_eve_image/eden.update_eve_image.tests.txt
- tests/update_eve_image/testdata/revert_eve_image_update.txt
- tests/update_eve_image/testdata/update_eve_image_http.txt
- tests/workflow/eden.workflow.tests.txt
Add the ability to revert eve image update onto previous one (defined in config).
> reset eve image update

- processing/Dockerfile
> Fixing a version mismatch

- Dockerfile
- eserver/Dockerfile
> Moving Eden to eve-alpine

- tests/hardware_reboot/testdata/hardware_usb_reboot.txt
Added reboot detector 
Test is working on Xen 
https://github.com/lf-edge/eden/pull/546#pullrequestreview-613255388
@eriknordmark @giggsoff  @sadov 
> Reboot test with USB changes

- cmd/edenConfig.go
- cmd/edenSetup.go
- cmd/eve.go
- docs/eve-models.md
- pkg/controller/device.go
- pkg/defaults/defaults.go
- pkg/defaults/templates.go
- pkg/models/devModel.go
- pkg/models/gcp.go
- pkg/models/general.go
- pkg/models/parallels.go
- pkg/models/qemu.go
- pkg/models/rpi.go
- pkg/models/vbox.go
- pkg/utils/config.go
The ability to provide file with devmodel overwrites.
> devmodel file support

- tests/eclient/Makefile
- tests/eclient/image/Dockerfile
- tests/eclient/image/halt
- tests/eclient/image/reboot
- tests/eclient/testdata/com-pt_test.txt
- tests/escript/README.md
- tests/escript/go-internal/testscript/cmd.go
The [test](tests/eclient/testdata/com-pt_test.txt) verifies the passthrough of COM2 to the application. Can be executed with the command:
```
eden test tests/eclient/ -e com-pt_test
```
Signed-off-by: Oleg Sadov <oleg@zededa.com>
> COM passthrough test

- pkg/defaults/defaults.go
- pkg/eden/eden.go
- pkg/utils/config.go
- pkg/utils/params.go
We move to public clouds, so it is reasonable to set passwords where we can. 
> redis password

- docs/ipxe.md
Documentation about booting EVE on Equinix Metal.
> packet deployment

- tests/eclient/qemu+2usb.sh
- tests/hardware_reboot/README.md
- tests/hardware_reboot/eden.hardware_reboot.tests.txt
- tests/hardware_reboot/testdata/hardware_2usb_reboot.txt
Simple test of 2 USB passthrough functionality after reboot of guest
> Test app with two assigned USB devices

- README.md
Fixed quickstart
Fixed readme for multiple eth
Fixed WiFi support
> Updated readme for a quickstart

- cmd/edenSetup.go
- pkg/utils/downloaders.go
Generate installer image #544 
> installer image generation

- cmd/eve.go
Seems, it is Mac OS related problem with VM for Docker #602 
> mac os ips fix

- models/template_l1_NEXCOM-NIFE105.json
Signed-off-by: gkodali-zededa <gkodali@zededa.com>
> Missed updating ethernet cost for this model in my last commit

- cmd/edenPod.go
- cmd/podModify.go
- pkg/defaults/defaults.go
- pkg/expect/application.go
- pkg/expect/networkInstance.go
- pkg/expect/options.go
- tests/eclient/testdata/air-gapped-switch.txt
- tests/workflow/eden.workflow.tests.txt
air-gapped switch test with defined mac addresses
> air-gapped switch test with defined mac addresses

- cmd/edenPod.go
- docs/applications.md
- go.mod
- go.sum
- pkg/defaults/defaults.go
- pkg/expect/application.go
- pkg/expect/datastore.go
- pkg/expect/directory.go
- pkg/expect/expectation.go
- pkg/expect/image.go
- pkg/utils/config.go
- pkg/utils/container.go
- pkg/utils/files.go
- tests/eclient/testdata/mount.txt
- tests/workflow/eden.workflow.tests.txt
The ability to use local directory to create docker images in the local registry and use them as volume or as rootfs of app
> directory for mount volumes

- cmd/edenController.go
- docs/config.md
- docs/flow.md
- pkg/expect/baseOSImage.go
- pkg/expect/expectation.go
Fixes for readme and functionality of eveimage-update
> update EVE image fixes

- .github/workflows/eden_setup.yml
- cmd/edenConfig.go
- docs/flow.md
- pkg/eden/eden.go
- pkg/utils/config.go
Fix missing OVMF file for run arm64 on amd64.
> support for arm64 on amd64

- pkg/eve/volumes.go
- tests/eclient/testdata/mount.txt
Add mount column to `volume ls`
> mount in volume ls

- pkg/utils/templates.go
- tests/eclient/testdata/port_forward.txt
Seems, we cannot connect between apps on different slirp networks with libslirp0>=4.2
> check slirp version in port_forward test

- .github/workflows/eden.yml
- .github/workflows/eden_gcp.yml
- .yamllint
> log counting

- README.md
- data/helloeve/index.html
Changed quickstart to use custom nginx webpage
Updated Readme
Updated crucial information in  Readme for someone who wants to do eve install on a remote hardware (which is the most common case) 
> Hello eve and quickstart

- pkg/defaults/defaults.go
- pkg/eden/qemu.go
- pkg/utils/networking.go
> new adam version

- README.md
- cmd/edenSetup.go
Maybe helpful for MacOS users.
Signed-off-by: Oleg Sadov <oleg@zededa.com>
> Just about ZSH config

- cmd/edenVolume.go
- docs/applications.md
- pkg/defaults/defaults.go
- pkg/eve/volumes.go
- pkg/expect/application.go
- tests/eclient/testdata/mount.txt
Volume attach/detach functionality and test for it
> volume attach/detach and test

- cmd/eve.go
New command "eden eve update" proposed in https://github.com/lf-edge/eden/issues/622
> eden eve update

- cmd/edenTest.go
- docs/tests.md
- pkg/defaults/defaults.go
- tests/app/eden-config.yml
- tests/docker/eden-config.yml
- tests/eclient/eden-config.yml
- tests/flir/eden-config.yml
- tests/hardware_reboot/eden-config.yml
- tests/io_performance/eden-config.yml
- tests/phoronix/eden-config.yml
- tests/registry/eden-config.yml
- tests/update_eve_image/eden-config.yml
- tests/volume/eden-config.yml
- tests/workflow/eden-config.yml
Add information about unneeded test-bin option in test, fix and remove unneeded variants
> test-bin fix and remove unneeded

- .github/workflows/eden.yml
- cmd/edenSetup.go
- cmd/edenStart.go
- docs/config.md
- pkg/defaults/defaults.go
- pkg/defaults/templates.go
- pkg/utils/config.go
make cpu, ram and disk configurable
> make cpu, ram and disk configurable

- .github/workflows/validate.yml
- Makefile
- models/template_l1_GCP-2Intf-4G.json
- models/template_l1_MBI-6418A-T7H.json
- models/template_l1_OnLogic-CL210G-11-RS.json
This consists of two commits:
1. adds rudimentary model validation checks (I am sure we can add more) + hooks it up to our CI/CD workflow
2. fixes three of the model files based on the findings from the previous commits
> Adding rudimentary model validation checks and updating models accordingly

- models/template_l1_rpi4-2G.json
- models/template_l1_rpi4-4G.json
- models/template_l1_rpi4-8G.json
Signed-off-by: Kathy Giori <kathy.giori@gmail.com>
> add three rpi models 2G 4G 8G

- tests/escript/failScenario.txt
Add fatal_stacks output to Eden fail scenario
> include fatal_stacks checking into failScenario

- Makefile
- docs/applications.md
- docs/io-performance-tests.md
- pkg/defaults/defaults.go
- processing/README.md
- processing/entrypoint.sh
- tests/eclient/testdata/acl.txt
- tests/eclient/testdata/air-gapped-switch.txt
- tests/eclient/testdata/app_nonat.txt
- tests/eclient/testdata/com-pt_test.txt
- tests/eclient/testdata/disk.txt
- tests/eclient/testdata/eclient.txt
- tests/eclient/testdata/eclients.txt
- tests/eclient/testdata/host-only.txt
- tests/eclient/testdata/maridb.txt
- tests/eclient/testdata/mount.txt
- tests/eclient/testdata/networking_light.txt
- tests/eclient/testdata/ngnix.txt
- tests/eclient/testdata/nw_switch.txt
- tests/eclient/testdata/port_forward.txt
- tests/eclient/testdata/profile.txt
- tests/eclient/testdata/usb-pt_test.txt
- tests/flir/testdata/test_flir.txt
- tests/hardware_reboot/testdata/hardware_2usb_reboot.txt
- tests/io_performance/testdata/fio_tests.txt
- tests/network/testdata/deploy_app.txt
- tests/network/testdata/vlans.txt
- tests/phoronix/testdata/deploy_app.txt
- tests/volume/testdata/volumes_test.txt
Move tests to lfedge docker images and remove unneeded build steps.
> move tests to lfedge docker images

- cmd/edenStart.go
- cmd/eve.go
- docs/tap.md
- pkg/defaults/defaults.go
- pkg/eden/qemu.go
- pkg/models/common.go
- pkg/models/qemu.go
The ability to start with tap interface as the third one inside EVE Qemu with option `--with-tap`.
> the ability to start EVE with tap interface as the third

- pkg/eve/networks.go
- pkg/eve/volumes.go
This is tripping up tests on EVE right now in particular for https://github.com/lf-edge/eve/pull/2280
> Make handling of delete of network instances more robust

- cmd/edenPod.go
- cmd/edenVolume.go
- pkg/expect/directory.go
- pkg/expect/docker.go
- pkg/expect/expectation.go
- pkg/expect/http.go
- pkg/expect/options.go
- tests/volume/testdata/local_datastore.txt
- tests/workflow/eden.workflow.tests.txt
override datastore functionality to set particular datastore path for volumes
local datastore test
> override datastore functionality and local datastore test

- pkg/defaults/defaults.go
- pkg/eve/applications.go
- pkg/eve/networks.go
- pkg/eve/volumes.go
Rework Eden to support 0 state of objects as deleted.
> use 0 states as deleted from info messages

- cmd/edenPod.go
- pkg/defaults/defaults.go
- pkg/expect/options.go
- tests/eclient/image/entrypoint.sh
- tests/eclient/testdata/userdata.txt
- tests/escript/go-internal/testscript/testscript.go
- tests/workflow/eden.workflow.tests.txt
Test for large user data (about 90014 of raw data).
> large user data test

- models/template_l1_iEi_TANK-870-AI-E3-8G-2A.json
Signed-off-by: Kathy Giori <kathy.giori@gmail.com>
> add iEi Xeon E3 and update i7 models

- tests/update_eve_image/testdata/update_eve_image_http.txt
- tests/update_eve_image/testdata/update_eve_image_oci.txt
update eve versions in image update tests to more recent with the latest kernel inside
> update eve versions in image update tests

- tests/eclient/testdata/acl.txt
- tests/eclient/testdata/air-gapped-switch.txt
- tests/eclient/testdata/app_nonat.txt
- tests/eclient/testdata/com-pt_test.txt
- tests/eclient/testdata/disk.txt
- tests/eclient/testdata/eclient.txt
- tests/eclient/testdata/eclients.txt
- tests/eclient/testdata/host-only.txt
- tests/eclient/testdata/maridb.txt
- tests/eclient/testdata/metadata.txt
- tests/eclient/testdata/mount.txt
- tests/eclient/testdata/networking_light.txt
- tests/eclient/testdata/ngnix.txt
- tests/eclient/testdata/nw_switch.txt
- tests/eclient/testdata/port_forward.txt
- tests/eclient/testdata/profile.txt
- tests/eclient/testdata/reboot_test.txt
- tests/eclient/testdata/usb-pt_test.txt
- tests/eclient/testdata/userdata.txt
- tests/hardware_reboot/testdata/hardware_2usb_reboot.txt
- tests/volume/testdata/local_datastore.txt
- tests/volume/testdata/volumes_test.txt
Update and sync eclient image in tests
> update eclient image

- tests/README.md
Signed-off-by: Robert Buhren <robert@robertbuhren.de>
> Fix broken reference in tests/README.md

- pkg/controller/eapps/eappslog.go
- pkg/controller/einfo/einfo.go
- tests/eclient/testdata/port_switch.txt
We should rely on internal conversion in info output and extract string only from byte slice
> extract string from byte slice in info

- tests/eclient/testdata/port_switch.txt
> fix nit in port_switch test

- pkg/defaults/defaults.go
- tests/eclient/testdata/nodered.txt
- tests/workflow/eden.workflow.tests.txt
> nodered test

- .github/workflows/eden_gcp.yml
move to gcp auth with deprecation of service_account_key in setup-gcloud action
> move to gcp auth with deprecation of service_account_key

- .github/workflows/eden_gcp.yml
- cmd/edenGcp.go
- pkg/defaults/defaults.go
- pkg/defaults/templates.go
- pkg/linuxkit/gcp.go
- pkg/utils/config.go
Enable vTPM for GCP VMs and update Adam to support TPM
> use vTPM for GCP edge-nodes

- tests/lim/testdata/info_test.txt
I can see timeouts in info test on receive new info stage. In this PR I increase epoch to get new info message in info_test
> increase epoch to get new info message in info_test

- pkg/eve/volumes.go
show percentage for downloading volume (in `eden volume ls` output).
> show percentage for downloading volume

- tests/escript/go-internal/testscript/cmd.go
- tests/escript/go-internal/testscript/testscript.go
rework background processes to properly interrupt test  with contexts
> rework background processes to properly interrupt test

- eserver/pkg/manager/manager.go
- eserver/pkg/server/adminHandler.go
- eserver/pkg/server/http.go
add broad patterns for filenames to support nested directories in eserver
> allow to use nested directories in eserver

- cmd/edenGcp.go
- cmd/edenPacket.go
- cmd/edenSetup.go
- cmd/root.go
- go.mod
- go.sum
- pkg/defaults/defaults.go
- pkg/defaults/templates.go
- pkg/packet/packet.go
- pkg/utils/config.go
support for eden packet commands to run/delete servers on Equinix platform.
also this PR adds `ipxe-override` flag to override lines in ipxe config.
> packet support in eden commands

- cmd/edenPacket.go
fix default ipxe link for packet according to #736
> fix ipxe link for default context for packet

- cmd/edenRol.go
- cmd/root.go
- docs/eve-platforms.md
- go.mod
- go.sum
Signed-off-by: Aleksandrov Dmitriy <goodmobiledevices@gmail.com>
> Rack of Labs support in eden commands

- tests/eclient/image/pkg/go.mod
- tests/eclient/image/pkg/go.sum
- tests/eclient/image/pkg/main.go
Add new endpoint to store app info from EVE https://github.com/lf-edge/eve/pull/2451
> update eclient to support appinfo endpoint

- docs/io-performance-tests.md
- docs/test-running.md
- pkg/defaults/defaults.go
- tests/README.md
- tests/escript/README.md
- tests/escript/go-internal/testscript/doc.go
> refactoring - changed to lf-edge

- pkg/defaults/images.go
- tests/fsstress/fsstress_test.go
Seems old version is not exists in public repository
> update Ubuntu image

- cmd/edenPod.go
```
eden pod restart <name>
eden pod purge <name>
```
> Eden pod restart and purge commands

- cmd/edenPod.go
Seems purge operation expect to have new volumes to recreate them
> Pod purge command should purge volumes as part of work

- pkg/defaults/defaults.go
- tests/eclient/testdata/app_dhcp.txt
- tests/eclient/testdata/dhcp-server/entrypoint.sh
- tests/workflow/eden.workflow.tests.txt
> Add test to check recorded IP assignments for switch networks

- pkg/defaults/defaults.go
- pkg/eve/volumes.go
- tests/eclient/testdata/app_local_info.txt
Test for this functionality: https://github.com/lf-edge/eve/pull/2469
> Extend appinfo test with command requests

- tests/eclient/image/pkg/go.mod
- tests/eclient/image/pkg/go.sum
- tests/eclient/image/pkg/main.go
This is needed for: https://github.com/lf-edge/eden/pull/757
> Add location endpoint handler to eclient LPS

- cmd/edenController.go
- pkg/controller/device.go
- pkg/defaults/defaults.go
- pkg/device/device.go
> eden controller edge-node shutdown command support

- .github/workflows/eden.yml
- cmd/edenStart.go
- cmd/edenStop.go
- cmd/eve.go
- docs/eve-models.md
- pkg/defaults/defaults.go
- pkg/eden/eden.go
- pkg/eden/qemu.go
- tests/lim/testdata/info_test.txt
- tests/workflow/eden.workflow.tests.txt
Support for swtpm with EVE-OS in qemu
> SWTPM support for EVE QEMU

- cmd/certs.go
- cmd/edenSetup.go
- pkg/eden/eden.go
We should be able to configure grub options during EVE-OS setup
> Support for defining grub options during setup

- tests/eclient/testdata/dev_local_info.txt
- tests/eclient/testdata/shutdown_test.txt
Add check for ZDEVICE_STATE_SHUTTING_DOWN in shutdown_test
> ZDEVICE_STATE_SHUTTING_DOWN check in shutdown_test

- cmd/edenPod.go
- cmd/podModify.go
- pkg/expect/application.go
- pkg/expect/expectation.go
- pkg/expect/options.go
Support for the option defined in
https://github.com/lf-edge/eve/pull/2603
> Start delay option implementation

- tests/eclient/testdata/dev_local_info.txt
- tests/escript/README.md
- tests/escript/go-internal/testscript/cmd.go
- tests/escript/go-internal/testscript/doc.go
- tests/escript/go-internal/testscript/testdata/wait.txt
- tests/escript/go-internal/testscript/testscript.go
- tests/escript/go-internal/testscript/testscript_test.go
Additional output for failed background processes and named background processes with wait for defined name
> Updates for escripts

- .github/workflows/yetus.yml
> GH Action Apache Yetus upgrade 0.14

- .github/workflows/eden.yml
- .github/workflows/eden_gcp.yml
- pkg/defaults/defaults.go
- tests/eclient/testdata/app_local_info.txt
- tests/eclient/testdata/profile.txt
- tests/escript/README.md
- tests/escript/go-internal/testscript/testscript.go
- tests/workflow/eden.workflow.tests.txt
- tests/zfs/testdata/state_check.txt
Modify github workflow to run tests with zfs-enabled EVE
> Add zfs-enabled EVE to eden test

- .github/workflows/eden_gcp.yml
- tests/network/testdata/switch_net_vlans.txt
Fix name of eden_gcp test and reduce memory required for test to work on eden_gcp xen test
> Fix for eden_gcp test

- .github/workflows/eden.yml
- .github/workflows/eden_gcp.yml
- pkg/controller/device.go
- pkg/utils/x509.go
- tests/eclient/testdata/disk.txt
- tests/eclient/testdata/publish_location.txt
- tests/escript/go-internal/testscript/cmd.go
- tests/vnc/vnc_test.go
- tests/workflow/testdata/template_check.txt
Reduction of unneeded logs and tests fixes
> Tests fixes

- .golangci.yml
> Yetus fixes

- pkg/eve/applications.go
- pkg/eve/networks.go
- pkg/eve/state.go
- pkg/eve/volumes.go
- tests/vnc/vnc_test.go
> Ensure info processing order and remove Errorf

- .github/workflows/eden.yml
- .github/workflows/eden_emh_arm.yml
- .github/workflows/eden_gcp.yml
- .github/workflows/eden_setup.yml
- .github/workflows/golint.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/validate.yml
- .github/workflows/yetus.yml
Update GH runner and adjust additional repositories
> Move to ubuntu 22.04 in action

- tests/eclient/testdata/shutdown_test.txt
- tests/vnc/vnc_test.go
Fix error in vnc test and stabilize shutdown test
> Fix error in vnc test and stabilize shutdown test

- tests/eclient/testdata/app_dhcp.txt
We changed build of dhcping in previous image update so let use new one
inside the test.
> Update eclient image in app_dhcp test

- .github/workflows/eden_setup.yml
- cmd/edenSetup.go
- pkg/eden/eden.go
We can make EVE from git repo, but seems it is not work as expected with
changes from EVE-OS side.
> Fix make from git function

- pkg/eden/eden.go
Let's generate v2tlsbaseroot-certificates.pem as concatenation of
default certificate and root-certificate to be compatible with future
changes of EVE-OS.
> Add root-certificate to v2tlsbaseroot-certificates

- tests/eclient/testdata/app_local_info.txt
- tests/eclient/testdata/dev_local_info.txt
- tests/eclient/testdata/radio_silence.txt
We have retrial logic so let's remove check for intermediate errors
> Ignore intermediate errors

- pkg/defaults/defaults.go
- tests/update_eve_image/testdata/update_eve_image_http.txt
- tests/update_eve_image/testdata/update_eve_image_oci.txt
> Update EVE-OS versions

- tests/eclient/image/Dockerfile
For future benchmarks we can use sysbench utility
> Add sysbench utility to eclient

- pkg/defaults/defaults.go
- tests/eclient/testdata/maridb.txt
- tests/phoronix/testdata/deploy_app.txt
Expanding of mariadb test with oltp sysbench test
> Add sysbench to mariadb test

- cmd/edenController.go
- cmd/eve.go
- go.mod
- go.sum
- pkg/controller/baseOs.go
- pkg/controller/cloud.go
- pkg/controller/device.go
- pkg/defaults/defaults.go
- pkg/device/device.go
- pkg/expect/baseOSImage.go
- tests/update_eve_image/testdata/update_eve_image_oci.txt
We should support novel BaseOS configuration as well as BaseOSConfig.
Also we have no test for retry of BaseOS image update, let's implement it.
> BaseOS configuration implementation and test for retry

- tests/docker/testdata/10dockers_test.txt
- tests/docker/testdata/2dockers_test.txt
- tests/eclient/testdata/networking_light.txt
- tests/eclient/testdata/ngnix.txt
- tests/eclient/testdata/nw_switch.txt
- tests/network/testdata/test_networking.txt
Fix some spelling issues in tests
> Fix spelling issues

- .github/workflows/eden.yml
- .github/workflows/eden_gcp.yml
- .github/workflows/eden_setup.yml
- .github/workflows/unit.yml
- Dockerfile
- eserver/Dockerfile
- processing/Dockerfile
- sdn/vm/Dockerfile
- tests/flir/image/Dockerfile
- tests/network/image/Dockerfile
Update packages and GH actions
> Update packages and GH actions

- .github/workflows/eden.yml
- .github/workflows/eden_emh_arm.yml
- .github/workflows/eden_gcp.yml
- .github/workflows/eden_setup.yml
- .github/workflows/publish.yml
- .github/workflows/release.yml
- .github/workflows/validate.yml
- .github/workflows/yetus.yml
- tests/eclient/image/Dockerfile
Update GH actions versions and eclient base images
> Update versions of GH actions and eclient

- .github/workflows/eden_emh_arm.yml
- .github/workflows/eden_gcp.yml
- .github/workflows/publish.yml
- cmd/edenController.go
- cmd/eve.go
- go.mod
- go.sum
- pkg/controller/cloud.go
- pkg/controller/device.go
- pkg/controller/functions.go
- pkg/defaults/defaults.go
- pkg/device/device.go
- pkg/expect/baseOSImage.go
Update BaseOS updates logic to use BaseOsVersion
> Update BaseOS updates logic to use BaseOsVersion

- .github/workflows/eden_setup.yml
- .github/workflows/publish.yml
- Makefile
Not fully tested (my fork does not have privileges to push lfedge images).
> Makefile target to build/publish eden-sdn image

- cmd/edenStart.go
- pkg/openevec/start.go
eden start should be able to set cfg.Runtime.ZedControlURL
> Set cfg.Runtime.ZedControlURL for eden start

- .golangci.yml
Allow to use replacements in go mod
> Allow to use replacements in go mod

- go.mod
- go.sum
- pkg/defaults/defaults.go
To AppInstanceConfig the following fields are added:
* Service - run app instance as a service container in the host/dom0
* CloudInitVersion - the version of the cloud-init config
To the Adapter config the following field is added:
* EthVf - the structure that describes information regarding Virtual Function
To the PhysicalIO config the following field is added:
* Vflist - list of Virtual Functions (VF) for given Physical Function (PF)
To storage types enum the following value is added:
* Target_AppCustom - for possible DTS usage
To the ContentTree config the following field is added:
* CustomMetaData - an arbitrary string, usage depends on the content purpose
To Volume config the following field is added:
* Target - рow the volume will be presented to the instance
To VmConfig the …
> Update the EVE API version.

- tests/eclient/testdata/dev_local_info.txt
- tests/lim/testdata/metric_test.txt
- tests/reboot/reboot_test.go
- tests/volume/testdata/local_datastore.txt
1. handle empty reboot reason
2. remove wrong metric test
3. refactoring of dev_local_info test
4. add sleep before download in local_datastore
> Several tests fixes

- cmd/adam.go
- cmd/certs.go
- cmd/edenClean.go
- cmd/edenConfig.go
- cmd/edenPod.go
- cmd/edenSetup.go
- cmd/edenStart.go
- cmd/edenStatus.go
- cmd/edenStop.go
- cmd/eserver.go
- cmd/eve.go
- cmd/flowlog.go
- cmd/info.go
- cmd/log.go
- cmd/metric.go
- cmd/redis.go
- cmd/root.go
- pkg/openevec/config.go
- pkg/openevec/eden.go
- pkg/openevec/edenConfig.go
- pkg/openevec/eve.go
- pkg/openevec/pod.go
- pkg/openevec/start.go
- pkg/openevec/status.go
> Remove runtime arguments

- cmd/edenConfig.go
- pkg/openevec/config.go
Those variables were set, but never used
Signed-off-by: Pavel Abramov <uncle.decart@gmail.com>
> Remove unused config variables

- cmd/edenConfig.go
- pkg/openevec/config.go
- pkg/openevec/defaults.go
Below are small changes in order to use eden as library more easily
> Testing framework fixes

- .github/actions/publish-logs/action.yml
- .github/actions/run-eden-test/action.yml
- .github/actions/setup-environment/action.yml
- .github/workflows/test.yml
- tests/workflow/networking.tests.txt
This PR creates GH actions to run separated tests. It's still WIP, because I want to test this workflows with runners provided by LF-EDGE
> GH actions for new tests

- .github/actions/run-eden-test/action.yml
- .github/actions/setup-environment/action.yml
- .github/workflows/test.yml
For eden test to use PR build tag of eve
> to use specific version of eve for the PR builds

- .github/workflows/eden_setup.yml
We have not enough space to store all images, let's do cleanup
> Clean in setup workflow to reduce storage usage

- pkg/eve/applications.go
I can see out of range error in case of no IpAddress
> Fix out of range error

- cmd/debug.go
Remove commented code which is not used
> Remove zombie code

- pkg/defaults/defaults.go
- pkg/eden/qemu.go
> fix : qemu uses kvm accelartion on Darwin arm64

- pkg/defaults/defaults.go
- pkg/evetestkit/utils.go
- Eve : to version 13.3.0
- Evetestkit : detect app halting state
- Evetestkit : add api to reboot eve node
> Evetestkit and Eve version Update

- pkg/evetestkit/utils.go
- tests/vcom/vcom_test.go
A few changes I cherry-picked from NeoEden, nothing major or changing : 
- add logging with timestamp functions
- deploy pre-configured vms like Ubuntu
- vm reuse if test is not destructive
- copying multiple test scripts at once
> Evetestkit Update

- tests/eclient/testdata/ctrl_cert_change.txt
Fix error message when server signing certificate does not match the uploaded one
> Add better error mesage to ctrl_cert_change test

- .github/actions/publish-logs/action.yml
- .github/workflows/eden_emh_arm.yml
- .github/workflows/eden_gcp.yml
- .github/workflows/yetus.yml
bumped up the actions/upload artifact version
> github/workflows: bumped up the actions/upload

- .github/workflows/eden.yml
- .github/workflows/eden_gcp.yml
switching GCP to manual use, since they've not been up to date
> GHA: retire GCP
